import type { Creator, NicheId, Platform, PlatformStats } from "./types";

/**
 * Platform stats from the last 20 organic videos. `spread` describes view
 * consistency: low spread = predictable creator, high spread = volatile.
 */
function ps(platform: Platform, followers: number, medianViews: number, spread = 0.4, engagementRate = 5): PlatformStats {
  return {
    platform,
    followers,
    medianViews,
    p25: Math.round(medianViews * (1 - spread * 0.9)),
    p75: Math.round(medianViews * (1 + spread * 1.6)),
    engagementRate,
  };
}
const ages = (a: number, b: number, c: number, d: number, e: number) => ({ "13–17": a, "18–24": b, "25–34": c, "35–44": d, "45+": e });
const geo = (...pairs: [string, number][]) => pairs.map(([code, pct]) => ({ code, pct }));

type Seed = Omit<Creator, "completedCampaigns" | "rating" | "responseTime" | "languages"> &
  Partial<Pick<Creator, "completedCampaigns" | "rating" | "responseTime" | "languages">>;

const c = (s: Seed): Creator => ({ completedCampaigns: 10, rating: 4.7, responseTime: "~4h", languages: ["English"], ...s });

const BEAUTY: NicheId[] = ["beauty"];

// Ids c1–c8 match the original demo personas (Supabase seed script).
export const CREATORS: Creator[] = [
  c({ id: "c1", name: "Maya Chen", handle: "@mayaglows", photo: "p-maya", city: "Los Angeles", country: "US", niches: ["beauty", "lifestyle"],
    interests: ["skincare routines", "sensitive skin", "morning routines", "clean beauty"],
    bio: "Former esthetician. Skincare routines for sensitive skin, no filters.",
    platforms: [ps("tiktok", 241_000, 52_000, 0.35, 6.1), ps("instagram", 182_000, 38_000, 0.4, 5.2), ps("youtube", 64_000, 21_000, 0.5, 4.2)],
    audience: { verified: true, femalePct: 78, ages: ages(4, 38, 34, 16, 8), topCountries: geo(["US", 62], ["CA", 9], ["GB", 7]), quality: 94 },
    pastBrands: ["CeraVe", "Glossier", "Daily Shield (Glow Inc.)"], samples: ["c-serum-hands", "c-serum-roller", "c-mask"], completedCampaigns: 23, rating: 4.9, responseTime: "~2h" }),
  c({ id: "c2", name: "Jordan Lee", handle: "@jordanlifts", photo: "p-jordan", city: "Austin", country: "US", niches: ["fitness", "food"],
    interests: ["gym routines", "protein snacks", "meal prep", "university students"],
    bio: "Strength coach. Honest supplement and snack reviews between sets.",
    platforms: [ps("tiktok", 138_000, 34_000, 0.45, 5.4), ps("instagram", 95_000, 19_000, 0.5, 4.9)],
    audience: { verified: true, femalePct: 42, ages: ages(5, 46, 33, 11, 5), topCountries: geo(["US", 71], ["CA", 6], ["GB", 5]), quality: 91 },
    pastBrands: ["Quest", "Gymshark"], samples: ["c-deadlift", "c-gym", "c-protein-bars"], completedCampaigns: 14 }),
  c({ id: "c3", name: "Sofia Reyes", handle: "@sofiaathome", photo: "p-sofia", city: "Miami", country: "US", niches: ["lifestyle", "beauty", "home"],
    interests: ["slow mornings", "home rituals", "self-care", "skincare routines"],
    bio: "Slow mornings, home rituals and the products that make them.", languages: ["English", "Spanish"],
    platforms: [ps("instagram", 240_000, 41_000, 0.55, 3.9), ps("tiktok", 120_000, 29_000, 0.6, 4.4), ps("youtube", 88_000, 26_000, 0.5, 3.4)],
    audience: { verified: true, femalePct: 82, ages: ages(2, 29, 41, 19, 9), topCountries: geo(["US", 58], ["MX", 9], ["CA", 6]), quality: 89 },
    pastBrands: ["Daily Shield (Glow Inc.)", "Aesop"], samples: ["c-coffee", "c-serum-eucalyptus", "c-avocado-toast"], completedCampaigns: 31 }),
  c({ id: "c4", name: "Dev Patel", handle: "@devexplains", photo: "p-dev", city: "Toronto", country: "CA", niches: ["tech", "education"],
    interests: ["gadgets", "productivity", "desk setups"],
    bio: "Gadget reviews and productivity setups, explained in under 60 seconds.",
    platforms: [ps("youtube", 120_000, 46_000, 0.4, 4.1), ps("tiktok", 74_000, 22_000, 0.5, 3.8)],
    audience: { verified: true, femalePct: 24, ages: ages(3, 32, 40, 17, 8), topCountries: geo(["US", 41], ["CA", 34], ["IN", 9]), quality: 92 },
    pastBrands: ["Anker", "Notion"], samples: ["c-desk", "c-earbuds", "c-phone"], completedCampaigns: 19, responseTime: "~1d" }),
  c({ id: "c5", name: "Ava Kim", handle: "@avaeats", photo: "p-ava", city: "New York", country: "US", niches: ["food", "lifestyle"],
    interests: ["15-minute recipes", "healthy snacks", "NYC food"],
    bio: "15-minute recipes and NYC snack hunts.",
    platforms: [ps("tiktok", 112_000, 31_000, 0.4, 6.4), ps("instagram", 67_000, 15_000, 0.45, 6.2)],
    audience: { verified: true, femalePct: 69, ages: ages(3, 36, 38, 15, 8), topCountries: geo(["US", 74], ["CA", 5], ["KR", 4]), quality: 93 },
    pastBrands: ["Siete", "RXBAR"], samples: ["c-bowl", "c-avocado-toast", "c-salad"], completedCampaigns: 11, rating: 4.9 }),
  c({ id: "c6", name: "Liam Carter", handle: "@liamwanders", photo: "p-liam", city: "Sydney", country: "AU", niches: ["lifestyle"],
    interests: ["travel", "cinematic", "adventure"],
    bio: "Cinematic travel films from 40+ countries.",
    platforms: [ps("instagram", 310_000, 61_000, 0.5, 3.2), ps("youtube", 150_000, 72_000, 0.45, 3.9)],
    audience: { verified: true, femalePct: 47, ages: ages(2, 30, 39, 20, 9), topCountries: geo(["AU", 31], ["US", 28], ["GB", 12]), quality: 90 },
    pastBrands: ["GoPro"], samples: ["c-beach", "c-mountains", "c-coffee"], completedCampaigns: 27, responseTime: "~1d" }),
  c({ id: "c7", name: "Nora Ali", handle: "@noraali", photo: "p-nora", city: "Chicago", country: "US", niches: ["fashion", "beauty"],
    interests: ["GRWM", "capsule wardrobe", "makeup", "college style"],
    bio: "Get-ready-with-me, capsule wardrobes and beauty crossovers.",
    platforms: [ps("instagram", 145_000, 29_000, 0.4, 4.6), ps("tiktok", 98_000, 33_000, 0.5, 5.8)],
    audience: { verified: true, femalePct: 84, ages: ages(5, 46, 32, 12, 5), topCountries: geo(["US", 66], ["CA", 8], ["GB", 6]), quality: 92 },
    pastBrands: ["Aritzia", "Fenty"], samples: ["c-flatlay", "c-brushes", "c-pump"], completedCampaigns: 18 }),
  c({ id: "c8", name: "Kai Wong", handle: "@kaiplays", photo: "p-kai", city: "Vancouver", country: "CA", niches: ["gaming", "tech"],
    interests: ["indie games", "setup tours"],
    bio: "Indie game deep dives and setup tours.",
    platforms: [ps("youtube", 89_000, 31_000, 0.5, 5.0), ps("tiktok", 60_000, 18_000, 0.6, 4.8)],
    audience: { verified: true, femalePct: 21, ages: ages(9, 47, 30, 10, 4), topCountries: geo(["US", 44], ["CA", 29], ["GB", 7]), quality: 88 },
    pastBrands: ["Razer"], samples: ["c-earbuds", "c-phone", "c-workspace"], completedCampaigns: 9, responseTime: "~8h" }),
  c({ id: "c9", name: "Chloe Martin", handle: "@chloeskin", photo: "p-chloe", city: "Vancouver", country: "CA", niches: BEAUTY,
    interests: ["ingredient breakdowns", "serums", "dermatologist tips", "skincare routines"],
    bio: "Ingredient-first serum reviews. Dermatologist-approved routines.",
    platforms: [ps("tiktok", 131_000, 41_000, 0.3, 7.2), ps("instagram", 88_000, 22_000, 0.35, 6.8)],
    audience: { verified: true, femalePct: 86, ages: ages(5, 44, 33, 12, 6), topCountries: geo(["CA", 41], ["US", 38], ["GB", 6]), quality: 96 },
    pastBrands: ["The Ordinary", "Daily Shield (Glow Inc.)"], samples: ["c-serum-white", "c-tube", "c-jars"], completedCampaigns: 16, rating: 4.9, responseTime: "~3h" }),
  c({ id: "c10", name: "Priya Shah", handle: "@priyaglow", photo: "p-priya", city: "New York", country: "US", niches: BEAUTY,
    interests: ["melanin-rich skin", "before/after", "brightening", "skincare routines"],
    bio: "Glow-ups for melanin-rich skin. Weekly before/afters.",
    platforms: [ps("tiktok", 96_000, 33_000, 0.3, 7.6), ps("instagram", 54_000, 14_000, 0.35, 7.1)],
    audience: { verified: true, femalePct: 81, ages: ages(4, 46, 32, 12, 6), topCountries: geo(["US", 69], ["IN", 11], ["CA", 5]), quality: 95 },
    pastBrands: ["Topicals"], samples: ["c-serum-stones", "c-facial", "c-serum-blue"], completedCampaigns: 8, rating: 4.8, responseTime: "~2h" }),
  c({ id: "c11", name: "Amara Okafor", handle: "@amaraglow", photo: "p-amara", city: "Atlanta", country: "US", niches: ["beauty", "fashion"],
    interests: ["GRWM", "makeup prep", "skincare routines"],
    bio: "GRWM, makeup and the skincare underneath it.",
    platforms: [ps("instagram", 126_000, 27_000, 0.4, 5.1), ps("tiktok", 150_000, 38_000, 0.45, 5.9), ps("youtube", 40_000, 14_000, 0.5, 4.0)],
    audience: { verified: true, femalePct: 80, ages: ages(3, 37, 38, 15, 7), topCountries: geo(["US", 71], ["GB", 8], ["NG", 6]), quality: 93 },
    pastBrands: ["Fenty", "Daily Shield (Glow Inc.)"], samples: ["c-brushes", "c-serum-roller", "c-pump"], completedCampaigns: 21 }),
  c({ id: "c12", name: "Ella Novak", handle: "@ellanovak", photo: "p-ella", city: "Denver", country: "US", niches: ["beauty", "entertainment"],
    interests: ["lazy skincare", "comedy", "skincare routines"],
    bio: "Funny, fast skincare for people who hate 10-step routines.",
    platforms: [ps("tiktok", 162_000, 47_000, 0.55, 6.6), ps("youtube", 58_000, 24_000, 0.5, 4.6)],
    audience: { verified: true, femalePct: 76, ages: ages(4, 39, 35, 15, 7), topCountries: geo(["US", 72], ["CA", 8], ["GB", 5]), quality: 91 },
    pastBrands: ["Bubble", "Daily Shield (Glow Inc.)"], samples: ["c-mask", "c-tube", "c-serum-shadow"], completedCampaigns: 12 }),
  c({ id: "c13", name: "Hannah Brooks", handle: "@hannahbuilds", photo: "p-hannah", city: "Boston", country: "US", niches: ["business", "education"],
    interests: ["founder diaries", "small business", "productivity"],
    bio: "Founder diaries and small-business growth tactics.",
    platforms: [ps("instagram", 40_000, 9_000, 0.4, 3.0), ps("tiktok", 71_000, 18_000, 0.5, 4.0)],
    audience: { verified: true, femalePct: 55, ages: ages(1, 18, 44, 26, 11), topCountries: geo(["US", 64], ["GB", 9], ["CA", 7]), quality: 94 },
    pastBrands: ["Shopify"], samples: ["c-desk", "c-workspace", "c-coffee"], completedCampaigns: 15, responseTime: "~1d" }),
  c({ id: "c14", name: "Lena Park", handle: "@lenapark", photo: "p-lena", city: "Seattle", country: "US", niches: BEAUTY,
    interests: ["texture shots", "ASMR", "skincare routines", "K-beauty"],
    bio: "Slow, aesthetic skincare. Texture shots and ASMR application.", languages: ["English", "Korean"],
    platforms: [ps("tiktok", 118_000, 28_000, 0.35, 5.0), ps("instagram", 98_000, 19_000, 0.4, 4.4)],
    audience: { verified: true, femalePct: 79, ages: ages(5, 42, 34, 13, 6), topCountries: geo(["US", 73], ["CA", 7], ["KR", 5]), quality: 92 },
    pastBrands: ["Laneige"], samples: ["c-serum-shadow", "c-bottles", "c-serum-eucalyptus"], completedCampaigns: 10 }),
  c({ id: "c15", name: "Zoe Bennett", handle: "@zoebeauty", photo: "p-zoe", city: "Boston", country: "US", niches: ["beauty", "education"],
    interests: ["30-day trials", "before/after", "college skincare", "university students"],
    bio: "30-day product trials with honest before/afters. Grad student.",
    platforms: [ps("tiktok", 88_000, 26_000, 0.35, 6.3), ps("instagram", 61_000, 13_000, 0.4, 6.0)],
    audience: { verified: true, femalePct: 83, ages: ages(6, 53, 26, 10, 5), topCountries: geo(["US", 70], ["CA", 6], ["GB", 6]), quality: 93 },
    pastBrands: ["Starface"], samples: ["c-facial", "c-serum-white", "c-pump"], completedCampaigns: 7 }),
  c({ id: "c16", name: "Mia Torres", handle: "@miatorres", photo: "p-mia", city: "Los Angeles", country: "US", niches: ["beauty", "fashion"],
    interests: ["unboxings", "first impressions", "GRWM", "makeup"],
    bio: "Makeup artist. Unboxings, first impressions and GRWMs.", languages: ["English", "Spanish"],
    platforms: [ps("tiktok", 140_000, 36_000, 0.45, 5.2), ps("instagram", 115_000, 21_000, 0.45, 4.8)],
    audience: { verified: true, femalePct: 77, ages: ages(4, 41, 35, 13, 7), topCountries: geo(["US", 64], ["MX", 10], ["CA", 5]), quality: 90 },
    pastBrands: ["Rare Beauty"], samples: ["c-brushes", "c-flatlay", "c-serum-roller"], completedCampaigns: 13 }),
  c({ id: "c17", name: "Rachel Kim", handle: "@rachelkimskin", photo: "p-rachel", city: "San Francisco", country: "US", niches: BEAUTY,
    interests: ["K-beauty", "clinical skincare", "reviews"],
    bio: "K-beauty and clinical skincare, reviewed side by side.",
    platforms: [ps("instagram", 205_000, 32_000, 0.5, 3.6), ps("tiktok", 90_000, 24_000, 0.55, 4.1)],
    audience: { verified: true, femalePct: 74, ages: ages(3, 34, 38, 17, 8), topCountries: geo(["US", 61], ["KR", 8], ["CA", 7]), quality: 88 },
    pastBrands: ["Cosrx", "Laneige"], samples: ["c-jars", "c-serum-blue", "c-bottles"], completedCampaigns: 26, responseTime: "~1d" }),
  c({ id: "c18", name: "Jess Alvarez", handle: "@jessglows", photo: "p-jess", city: "Phoenix", country: "US", niches: BEAUTY,
    interests: ["drugstore dupes", "budget skincare", "college skincare"],
    bio: "Drugstore vs luxury skincare dupes.", languages: ["English", "Spanish"],
    platforms: [ps("tiktok", 72_000, 21_000, 0.5, 6.0), ps("instagram", 47_000, 9_000, 0.5, 5.2)],
    audience: { verified: true, femalePct: 80, ages: ages(5, 50, 28, 11, 6), topCountries: geo(["US", 77], ["MX", 6], ["CA", 4]), quality: 90 },
    pastBrands: ["e.l.f."], samples: ["c-serum-stones", "c-mask", "c-tube"], completedCampaigns: 5, responseTime: "~1d" }),
  c({ id: "c19", name: "Marcus Reed", handle: "@marcusreedfit", photo: "p-marcus", city: "Charlotte", country: "US", niches: ["fitness", "food"],
    interests: ["home workouts", "high-protein meal prep", "protein snacks"],
    bio: "Home workouts and high-protein meal prep.",
    platforms: [ps("tiktok", 84_000, 27_000, 0.35, 6.2), ps("instagram", 52_000, 12_000, 0.4, 5.6)],
    audience: { verified: true, femalePct: 38, ages: ages(3, 40, 37, 14, 6), topCountries: geo(["US", 76], ["CA", 5], ["GB", 4]), quality: 95 },
    pastBrands: ["Built Bar"], samples: ["c-crunches", "c-protein-bars", "c-gym"], completedCampaigns: 9, rating: 4.8 }),
  c({ id: "c20", name: "Tasha Green", handle: "@tashaeatsclean", photo: "p-tasha", city: "Portland", country: "US", niches: ["food", "fitness", "parenting"],
    interests: ["healthy snacks", "snack swaps", "busy parents"],
    bio: "Clean eating for busy parents. Snack swaps that actually taste good.",
    platforms: [ps("tiktok", 64_000, 19_000, 0.3, 6.8), ps("instagram", 38_000, 8_500, 0.35, 6.4)],
    audience: { verified: true, femalePct: 72, ages: ages(1, 22, 41, 24, 12), topCountries: geo(["US", 81], ["CA", 6], ["AU", 3]), quality: 96 },
    pastBrands: ["KIND"], samples: ["c-salad", "c-steak-salad", "c-bowl"], completedCampaigns: 12, rating: 4.9 }),
  c({ id: "c21", name: "Isla Grant", handle: "@islagrantskin", photo: "p-isla", city: "London", country: "GB", niches: BEAUTY,
    interests: ["skincare routines", "UK beauty"],
    bio: "UK skincare editor turned creator.",
    platforms: [ps("tiktok", 150_000, 39_000, 0.35, 5.4), ps("instagram", 132_000, 26_000, 0.4, 5.0)],
    audience: { verified: true, femalePct: 82, ages: ages(4, 43, 34, 13, 6), topCountries: geo(["GB", 58], ["US", 14], ["IE", 6]), quality: 93 },
    pastBrands: ["Boots"], samples: ["c-serum-eucalyptus", "c-jars", "c-facial"], completedCampaigns: 17 }),
  c({ id: "c22", name: "Bree Collins", handle: "@breecollins", photo: "p-bree", city: "Los Angeles", country: "US", niches: ["beauty", "fashion"],
    interests: ["red carpet", "GRWM"],
    bio: "Beauty, fashion and red-carpet prep.",
    platforms: [ps("tiktok", 1_400_000, 260_000, 0.6, 3.4), ps("instagram", 1_200_000, 190_000, 0.55, 2.9)],
    audience: { verified: true, femalePct: 76, ages: ages(5, 40, 33, 14, 8), topCountries: geo(["US", 55], ["GB", 9], ["CA", 7]), quality: 84 },
    pastBrands: ["Dior", "Sephora"], samples: ["c-brushes", "c-flatlay", "c-amber"], completedCampaigns: 64, responseTime: "~3d" }),
  c({ id: "c23", name: "Nina Duarte", handle: "@ninaduarte", photo: "p-nina", city: "Miami", country: "US", niches: ["beauty", "fashion"],
    interests: ["beauty hacks", "bold looks"],
    bio: "Bold looks and quick beauty hacks.",
    platforms: [ps("tiktok", 95_000, 6_500, 0.8, 2.4), ps("instagram", 33_000, 3_000, 0.8, 2.1)],
    audience: { verified: false, femalePct: 71, ages: ages(6, 44, 31, 13, 6), topCountries: geo(["US", 48], ["BR", 18], ["MX", 9]), quality: 68 },
    pastBrands: [], samples: ["c-pump", "c-amber", "c-soaps"], completedCampaigns: 3, rating: 4.3, responseTime: "~1d" }),
  c({ id: "c24", name: "Theo Nguyen", handle: "@theoskincare", photo: "p-theo", city: "San Diego", country: "US", niches: ["beauty", "lifestyle"],
    interests: ["men's skincare", "skincare routines", "comedy"],
    bio: "Skincare for guys who never had a routine.",
    platforms: [ps("tiktok", 126_000, 37_000, 0.4, 6.0), ps("instagram", 84_000, 15_000, 0.45, 5.3)],
    audience: { verified: true, femalePct: 34, ages: ages(4, 48, 33, 10, 5), topCountries: geo(["US", 75], ["CA", 6], ["AU", 4]), quality: 92 },
    pastBrands: ["Hims"], samples: ["c-tube", "c-bottles", "c-amber"], completedCampaigns: 6 }),
  c({ id: "c25", name: "Coco Hart", handle: "@cocomoves", photo: "p-coco", city: "Los Angeles", country: "US", niches: ["fitness", "fashion"],
    interests: ["dance cardio", "athleisure", "gym routines"],
    bio: "Dance cardio and athleisure styling.",
    platforms: [ps("tiktok", 210_000, 64_000, 0.5, 6.0), ps("instagram", 76_000, 18_000, 0.5, 5.9)],
    audience: { verified: true, femalePct: 79, ages: ages(6, 45, 33, 11, 5), topCountries: geo(["US", 69], ["CA", 7], ["GB", 5]), quality: 90 },
    pastBrands: ["Alo Yoga", "Celsius"], samples: ["c-crunches", "c-gym", "c-avocado-toast"], completedCampaigns: 8, responseTime: "~2h" }),
  c({ id: "c26", name: "Skylar Brooks", handle: "@skylarstrong", photo: "p-skylar", city: "Nashville", country: "US", niches: ["fitness", "food", "education"],
    interests: ["strength training", "protein snacks", "university students", "gym routines"],
    bio: "Strength training for women. Protein-first snacks. Senior at Vanderbilt.",
    platforms: [ps("tiktok", 77_000, 24_000, 0.3, 6.9), ps("instagram", 44_000, 10_000, 0.35, 6.3)],
    audience: { verified: true, femalePct: 83, ages: ages(3, 55, 29, 9, 4), topCountries: geo(["US", 79], ["CA", 6], ["AU", 3]), quality: 95 },
    pastBrands: [], samples: ["c-deadlift", "c-protein-bars", "c-salad"], completedCampaigns: 6, rating: 4.8, responseTime: "~3h" }),
];

export const creatorById = (id: string) => CREATORS.find((c) => c.id === id);

export function statsFor(c: Creator, platform: Platform) {
  return c.platforms.find((p) => p.platform === platform);
}

export function primaryStats(c: Creator) {
  return [...c.platforms].sort((a, b) => b.medianViews - a.medianViews)[0];
}
